### ISSUE TITLE
Content-Encoding gzip

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#975]
Failed to download file from this URL
http://123musiq.mobi/songs/info/19659 
there is actually file in the URL but its gzip 
this URL only available in mobile mode 

03-23 11:55:57.947 3850-3850/download I/FileDownloader.FileDownloadProperties: init properties 2
                                                                                      load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3; file.non-pre-allocation=FALSE; broadcast.completed=FALSE; download.trial-connection-head-method=FALSE
03-23 11:55:57.950 3850-3850/download D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext GDMApplication
03-23 11:55:57.963 3850-3850/download V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
03-23 11:55:58.231 3850-3850/download D/FileDownloader.FileDownloadServiceUIGuard: onServiceConnected ComponentInfo{download/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@fbb341c
03-23 11:55:58.231 3850-3850/download V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
03-23 11:55:58.232 3850-3971/download V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
03-23 11:56:10.591 3850-3850/download D/FileDownloader.DownloadTask: setPath /storage/emulated/0/GDM/Kannile_Poika_320.mp3
03-23 11:56:10.592 3850-3850/download D/FileDownloader.DownloadTask: setListener com.liulishuo.filedownloader1.demo.notifications.NotificationListener@1776276
03-23 11:56:10.592 3850-3850/download V/FileDownloader.DownloadTaskHunter: call start Url[http://123musiq.mobi/cgi-bin/floader.cgi?fileID=19608&intVal=1&Auth=RyLp3VyyZ3y2QfMBKzQR1w==&load=Kannile_Poika_320.mp3], Path[/storage/emulated/0/GDM/Kannile_Poika_320.mp3] Listener[com.liulishuo.filedownloader1.demo.notifications.NotificationListener@1776276], Tag[null]
03-23 11:56:10.595 3850-3850/download V/FileDownloader.DownloadTaskHunter: the task[421124599] has been into the launch pool.
03-23 11:56:10.597 3850-4403/download V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
03-23 11:56:10.598 3850-4403/download D/FileDownloader.FileDownloadMessenger: notify begin 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002
03-23 11:56:10.599 3850-4403/download V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@9043d13 by 11 
03-23 11:56:10.603 3850-4403/download V/FileDownloader.FileDownloadList: add list in all 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002 11 1
03-23 11:56:10.604 3927-3942/download:filedownloader D/FileDownloader.FileDownloadManager: request start the task with url(http://123musiq.mobi/cgi-bin/floader.cgi?fileID=19608&intVal=1&Auth=RyLp3VyyZ3y2QfMBKzQR1w==&load=Kannile_Poika_320.mp3) path(/storage/emulated/0/GDM/Kannile_Poika_320.mp3) isDirectory(FALSE)
03-23 11:56:10.609 3927-3942/download:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 421124599 file not suit, exists[FALSE], directory[FALSE]
03-23 11:56:10.615 3850-4406/download D/FileDownloader.MessageSnapshotGate: ~~~callback 421124599 old[11] new[1] 1
03-23 11:56:10.615 3850-4406/download D/FileDownloader.FileDownloadMessenger: notify pending 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002
03-23 11:56:10.615 3850-4406/download D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-23 11:56:10.616 3850-4406/download D/FileDownloader.MessageSnapshotGate: ~~~callback 421124599 old[1] new[6] 1
03-23 11:56:10.616 3850-4406/download D/FileDownloader.FileDownloadMessenger: notify started 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002
03-23 11:56:10.616 3850-4406/download D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-23 11:56:10.616 3927-4405/download:filedownloader D/FileDownloader.DownloadMgrInitialParams: initial FileDownloader manager with the customize connection creator: com.liulishuo.filedownloader.connection.FileDownloadUrlConnection$Creator@77f7f70
03-23 11:56:10.618 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: <---- 421124599 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.0.79]}
03-23 11:56:11.165 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: ----> 421124599 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[no-store, no-cache, must-revalidate], CF-RAY=[3ffed33ba0992de5-BOM], Connection=[keep-alive], Content-Range=[bytes 0-0/65], Content-Type=[text/html; charset=UTF-8], Date=[Fri, 23 Mar 2018 06:26:12 GMT], Expires=[Thu, 19 Nov 1981 08:52:00 GMT], Pragma=[no-cache], Server=[cloudflare], Set-Cookie=[__cfduid=da8acd6b8d932b7ffe550099fb7c00cd51521786372; expires=Sat, 23-Mar-19 06:26:12 GMT; path=/; domain=.123musiq.mobi; HttpOnly, PHPSESSID=2e6hq44m5v3637c2kr59ntdb05; path=/], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1521786371163], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1521786370684]}
03-23 11:56:11.165 3927-4405/download:filedownloader D/FileDownloader.FileDownloadUtils: etag find null for task(421124599)
03-23 11:56:11.167 3850-4406/download D/FileDownloader.MessageSnapshotGate: ~~~callback 421124599 old[6] new[2] 1
03-23 11:56:11.167 3850-4406/download D/FileDownloader.FileDownloadMessenger: notify connected 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002
03-23 11:56:11.167 3850-4406/download D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-23 11:56:11.169 3927-4405/download:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 421124599 file not suit, exists[FALSE], directory[FALSE]
03-23 11:56:11.195 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: <---- 421124599 request header {Range=[bytes=0-], User-Agent=[FileDownloader/1.0.79]}
03-23 11:56:11.678 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: ----> 421124599 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[no-store, no-cache, must-revalidate], CF-RAY=[3ffed33ee13a2de5-BOM], Connection=[keep-alive], Content-Range=[bytes 0-64/65], Content-Type=[text/html; charset=UTF-8], Date=[Fri, 23 Mar 2018 06:26:13 GMT], Expires=[Thu, 19 Nov 1981 08:52:00 GMT], Pragma=[no-cache], Server=[cloudflare], Set-Cookie=[__cfduid=da8acd6b8d932b7ffe550099fb7c00cd51521786372; expires=Sat, 23-Mar-19 06:26:12 GMT; path=/; domain=.123musiq.mobi; HttpOnly, PHPSESSID=29m4732mj4s6bdivv4jppnm7q1; path=/], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1521786371676], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1521786371196]}
03-23 11:56:11.678 3927-4405/download:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for 421124599, is connected range[0, -1) current offset[0] with code[206]
03-23 11:56:11.684 3927-4405/download:filedownloader D/FileDownloader.FetchDataTask: start fetch(-1): range [0, -1), seek to[0]
03-23 11:56:11.689 3927-4405/download:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
03-23 11:56:11.706 3927-4405/download:filedownloader D/FileDownloader.FetchDataTask: require flushAndSync id[421124599] index[-1] offset[65], consume[14]
03-23 11:56:11.706 3927-4405/download:filedownloader D/FileDownloader.DownloadLaunchRunnable: the connection has been completed(-1): [0, -1)  65
03-23 11:56:11.731 3850-4406/download D/FileDownloader.MessageSnapshotGate: ~~~callback 421124599 old[2] new[-3] 1
03-23 11:56:11.732 3850-4406/download V/FileDownloader.FileDownloadList: remove 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002 left -3 0
03-23 11:56:11.733 3850-4406/download D/FileDownloader.FileDownloadMessenger: notify block completed 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002 FileDownloader-Flow-01
03-23 11:56:11.735 3850-4406/download D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-23 11:56:11.735 3850-4436/download D/FileDownloader.FileDownloadMessenger: notify completed 421124599@com.liulishuo.filedownloader.DownloadTask@bef3002
03-23 11:56:11.735 3850-4436/download V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@9043d13 by -3 
03-23 11:56:11.792 3850-3850/download D/FileDownloader.FileDownloadDatabase: refreshed data count: 0 , delete data count: 0, reset id count: 0. consume 2
03-23 11:56:11.792 3850-3850/download W/FileDownloader.FileDownloader: If you invoked this method, please remove it directly feel free, it doesn't need any longer

**Comment by Jeffin21** [comment]
Please check this issue

**Comment by Jacksgong** [comment]
by the default, `gzip` has already handled by the default  `FileDownloadConnection` which the real handler is `Http(s)UrlConnection` and on the deep layer is okhttp old version.

and I test the url the response said this resource is `chunked` so we download, and finally completed download, the follwoing log indicate the `request` and `response`:

```
03-23 11:56:10.618 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: <---- 421124599 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.0.79]}
03-23 11:56:11.165 3927-4405/download:filedownloader D/FileDownloader.ConnectTask: ----> 421124599 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[no-store, no-cache, must-revalidate], CF-RAY=[3ffed33ba0992de5-BOM], Connection=[keep-alive], Content-Range=[bytes 0-0/65], Content-Type=[text/html; charset=UTF-8], Date=[Fri, 23 Mar 2018 06:26:12 GMT], Expires=[Thu, 19 Nov 1981 08:52:00 GMT], Pragma=[no-cache], Server=[cloudflare], Set-Cookie=[__cfduid=da8acd6b8d932b7ffe550099fb7c00cd51521786372; expires=Sat, 23-Mar-19 06:26:12 GMT; path=/; domain=.123musiq.mobi; HttpOnly, PHPSESSID=2e6hq44m5v3637c2kr59ntdb05; path=/], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1521786371163], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1521786370684]}
```

So, I even don't know what's problem do you get, and why do you said download is failed?

**Comment by Jeffin21** [comment]
Please test download from this url 
http://123musiq.mobi/songs/info/19659 
There is 4 mp3 songs in it u can choose any of them , this website only avalible in mobile mood we can download the song using chrome but I couldn’t with file downloader.
Yes this is gzip but it’s different. Please recheck. Thank You

**Comment by Jeffin21** [comment]
Our our filedownloader it will show content type HTML but there is song in it

**Comment by Jacksgong** [comment]
@Jeffin21 If you can download it from chrome but not on FileDownloader, the problem must be on the request header, so please check the request headers from chrome and mock the same request headers on the FileDownloader and test again, thanks.

**Comment by Jeffin21** [comment]
We checked all the possibilities and it didn’t work , it’s chucked  filedownloader shows it’s html there is file in it. Check this url http://123musiq.mobi/songs/info/19659

**Comment by Jacksgong** [comment]
@Jeffin21 you also can test with [this tips](https://github.com/lingochamp/FileDownloader/wiki/Can't-download-for-some-Urls%3F)

**Comment by Jeffin21** [comment]
Thank you I’ll check

**Comment by Jacksgong** [comment]
ok. If you let me find out the problem the only way I can do is check the request headers from chrome because there are many people have the same problem solved by this way, and the tips on the wiki also were found out through check worked corrected request headers, and just find the differential.

**Comment by Jeffin21** [comment]
I didn’t get the 302 error code

**Comment by Jeffin21** [comment]
Hello, i checked with request header still getting the html code

**Comment by Jacksgong** [comment]
So If you tried same request headers to chrome on FileDownloader but got the different response headers and body I also don't know what's going on in `http://123musiq.mobi/songs/info/19659`.

---

If you not tried, please try it.

**Comment by Jacksgong** [comment]
I think this is not FileDownloader issue, it is because of `123musiq.mobi` protected its resource not to be unauthorized downloaded through checking special request headers. So if the unauthorized request headers she found she will response data with an html page instead of the real music, what is a very normal case.

**Comment by Jacksgong** [comment]
If `123musiq.mobi` is your company please ask them directly what's the problem with my request headers, why don't you give me correct music response, and then using the right request header they gave to you.
